# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Autonomous Navigation  # course name
code: AE640A # course code
instructor: Prof. Mangal Kothari  # course instructor
email: ae640a@gmail.com
description: > # this means to ignore newlines until "url:"
  This 9-credit graduate level course is designed to teach the essentials of
  robotics. The course would deal with dynamics and state estimation for various
  robotic systems, mainly focusing on the kalman filter and its family.
  It would also cover path planning and SLAM algorithms for these systems. Towards
  the end of the course advanced topics like cooperative localization may be discussed.

url: "https://ae640a.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-111494265-1

timezone: India/Kanpur
permalink: none

# Optional features
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  commands:
    output: true
    permalink: /commands/:title
  syllabus:
  updates:
  lectures:
    output: true

defaults:
  - scope:
      type: lectures
    values:
      layout: lecture
  - scope:
      type: syllabus
    values:
      layout: syllabus
  - scope:
      path: "_syllabus/winter17"
    values:
      category: winter17
  - scope:
      path: "_lectures/winter17"
    values:
      category: winter17
  - scope:
      path: "_updates/winter17"
    values:
      category: winter17

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown

# This is a bit of a hack, since we're using remark, which expects
# to render markdown itself, we need to prevent jekyll from picking
# it up and parsing it, however we would still like to use the templating
# features of jekyll so that we can just write slides alone, in a
# markdown file. Thus we override the extensions list so that jekyll does
# not treat .markdown files as markdown.
markdown_ext: "mkdown,mkdn,mkd,md"

query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

# Needed for Travis
exclude: [vendor]

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
